Repository eventespresso/eea-paypal-smart-buttons, pull requests merged in 2018-09, with the labels that each got.

#17 Fix PUE slug
  EE_Paypal_Smart_Buttons.class.php
Labels: category:pue-uxip-and-licensing, status:review, type:bug 🐞

#11 Bug/add inr
  CHANGELOG.md
  payment_methods/Paypal_Smart_Buttons/EEG_Paypal_Smart_Buttons.gateway.php
Labels: category:payment-methods, type:feature-request 🙏

#9 Bug/dont timeout so quick
  core/services/PayPalRestApiClient.php
Labels: category:payment-methods, status:needs-testing, type:bug 🐞

#21 Fixed error when logging errors
  payment_methods/Paypal_Smart_Buttons/EEG_Paypal_Smart_Buttons.gateway.php
Labels: category:payment-methods, status:merge, type:bug 🐞

#18 Change the wording used on the PayPal's pop-up
  scripts/ee_pp_smart_buttons.js
Labels: category:payment-methods, status:merge, type:bug 🐞
